import puppeteer from '@cloudflare/puppeteer';

const VERSION='1.5';
const DEFAULT_TIMEOUT_MS=10000;
const MAX_TIMEOUT_MS=12000;
const MAX_OBSERVATIONS=24;
const MAX_API_OBSERVATIONS=32;
const ALLOWED_PAGE_HOSTS=new Set(['live.ertflix.gr','www.antenna.gr']);
const APPROVED_HEADER_NAMES=new Set(['user-agent','referer','origin']);
const MEDIA_RE=/\.(?:m3u8|mpd|mp4|webm)(?:[?#]|$)/i;
const ERT_CHANNEL_LABELS=Object.freeze({ert1:['ert1','ερτ1'],ert2:['ert2','ερτ2'],ert3:['ert3','ερτ3'],ertnews:['ertnews','ερτnews','ertνεws']});

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});}
function authorized(request,env){const expected=String(env.RESOLVER_SHARED_TOKEN||'');return Boolean(expected)&&request.headers.get('authorization')===`Bearer ${expected}`;}
function safePageUrl(raw=''){const url=new URL(String(raw||'').trim());if(url.protocol!=='https:')throw new Error('Only HTTPS pages are allowed');if(!ALLOWED_PAGE_HOSTS.has(url.hostname.toLowerCase()))throw new Error('Page host is not allowlisted');return url;}
function sanitizeHeaders(headers={}){const out={};for(const [key,value] of Object.entries(headers||{})){const name=String(key||'').toLowerCase();if(!APPROVED_HEADER_NAMES.has(name))continue;const text=String(value||'').trim();if(!text||text.length>2048)continue;const canonical=name==='user-agent'?'User-Agent':name[0].toUpperCase()+name.slice(1);out[canonical]=text;}return out;}
function safeHeaderNames(headers={}){return [...new Set(Object.keys(headers||{}).map(key=>String(key||'').trim().toLowerCase()).filter(Boolean))].sort().slice(0,32);}
function timeoutFrom(body={}){const requested=Number(body?.capture?.timeoutMs)||DEFAULT_TIMEOUT_MS;return Math.max(2500,Math.min(MAX_TIMEOUT_MS,requested));}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
function normalizedChannelKey(channel={}){const value=String(channel.id||channel.originalId||channel.tvgId||channel.name||'');return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9α-ω]+/gi,'');}
function isHttpsRemote(raw=''){try{const u=new URL(String(raw||''));return u.protocol==='https:'&&u.hostname&&!u.hostname.endsWith('.local')&&u.hostname!=='localhost';}catch{return false;}}
function responseKind(contentType='',url=''){const type=String(contentType||'').toLowerCase();if(type.includes('dash+xml')||/\.mpd(?:[?#]|$)/i.test(url))return'dash';if(type.includes('mpegurl')||type.includes('x-mpegurl')||/\.m3u8(?:[?#]|$)/i.test(url))return'hls';if(type.startsWith('video/')||/\.(?:mp4|webm)(?:[?#]|$)/i.test(url))return'video';return'';}
function safeApiLocation(raw=''){try{const u=new URL(String(raw||''));return{host:u.hostname.toLowerCase().slice(0,253),pathname:u.pathname.slice(0,300)};}catch{return{host:'',pathname:''};}}

async function pageDiagnostics(page){try{return await page.evaluate(()=>{const safeHost=value=>{try{return new URL(value,location.href).hostname}catch{return''}};const label=el=>String(el.getAttribute('aria-label')||el.textContent||el.title||'').replace(/\s+/g,' ').trim().slice(0,80);const video=document.querySelector('video');return{title:String(document.title||'').slice(0,120),pathname:location.pathname,videoCount:document.querySelectorAll('video').length,iframeCount:document.querySelectorAll('iframe').length,buttonCount:document.querySelectorAll('button').length,iframeHosts:[...new Set([...document.querySelectorAll('iframe[src]')].map(el=>safeHost(el.src)).filter(Boolean))].slice(0,8),buttonLabels:[...new Set([...document.querySelectorAll('button,[role="button"]')].map(label).filter(Boolean))].slice(0,12),video:video?{paused:Boolean(video.paused),ended:Boolean(video.ended),readyState:Number(video.readyState)||0,networkState:Number(video.networkState)||0,currentTime:Number.isFinite(video.currentTime)?Math.round(video.currentTime*10)/10:0,currentSrcHost:safeHost(video.currentSrc||video.src||''),errorCode:video.error?.code||0}:null};});}catch{return{title:'',pathname:'',videoCount:0,iframeCount:0,buttonCount:0,iframeHosts:[],buttonLabels:[],video:null};}}
async function clickSelectedChannel(page,channel={}){const key=normalizedChannelKey(channel);const targets=ERT_CHANNEL_LABELS[key]||[];if(!targets.length)return{clicked:false,label:''};try{return await page.evaluate(targetsIn=>{const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9α-ω]+/gi,'');const targets=new Set(targetsIn.map(normalize));for(const node of document.querySelectorAll('button,[role="button"],a')){const raw=String(node.getAttribute('aria-label')||node.textContent||node.title||'').replace(/\s+/g,' ').trim();if(!raw||!targets.has(normalize(raw)))continue;try{node.click();return{clicked:true,label:raw.slice(0,80)};}catch{}}return{clicked:false,label:''};},targets);}catch{return{clicked:false,label:''};}}
async function nudgePlayback(page){try{await page.evaluate(async()=>{for(const video of document.querySelectorAll('video')){try{video.muted=true;await video.play();}catch{}}for(const selector of ['button.vjs-play-control','.brid-overlay-play-button','[aria-label="Play"]','[aria-label*="play" i]','.play-button','.player-play']){const el=document.querySelector(selector);if(el){try{el.click();}catch{}}}});}catch{}}

function makeObservation(request,url){const requestHeaders=request.headers();return{url,method:request.method(),resourceType:request.resourceType(),headers:sanitizeHeaders(requestHeaders),requestHeaderNames:safeHeaderNames(requestHeaders),responseStatus:null,responseContentType:'',redirectedFrom:'',finalUrl:'',finalStatus:null,finalContentType:'',finalKind:''};}

async function resolve(body,env){
  if(!env.BROWSER)throw new Error('Browser binding is not configured');
  const pageUrl=safePageUrl(body?.url);const timeoutMs=timeoutFrom(body);const observations=[];const byUrl=new Map();const mediaSeeds=new Set();const apiObservations=[];const apiSeen=new Set();let phase='page-load';let browser;const started=Date.now();
  try{
    browser=await puppeteer.launch(env.BROWSER);const page=await browser.newPage();page.setDefaultNavigationTimeout(timeoutMs);page.setDefaultTimeout(timeoutMs);
    page.on('request',request=>{try{const url=request.url();const chain=typeof request.redirectChain==='function'?request.redirectChain():[];const inherited=chain.some(parent=>mediaSeeds.has(parent.url()));const isSeed=MEDIA_RE.test(url);if(!isSeed&&!inherited)return;if(byUrl.has(url))return;if(isSeed)mediaSeeds.add(url);const item=makeObservation(request,url);item.redirectedFrom=chain.length?chain[chain.length-1].url():'';byUrl.set(url,item);observations.push(item);}catch{}});
    page.on('response',response=>{try{
      const url=response.url();const request=response.request();const status=response.status();const contentType=String(response.headers()?.['content-type']||'').split(';')[0].slice(0,120);const resourceType=String(request.resourceType()||'');
      if((resourceType==='xhr'||resourceType==='fetch')&&apiObservations.length<MAX_API_OBSERVATIONS){const loc=safeApiLocation(url);const key=`${resourceType}|${request.method()}|${loc.host}|${loc.pathname}|${status}|${phase}`;if(loc.host&&!apiSeen.has(key)){apiSeen.add(key);apiObservations.push({phase,resourceType,method:request.method(),host:loc.host,pathname:loc.pathname,status,contentType});}}
      const kind=responseKind(contentType,url);const chain=typeof request.redirectChain==='function'?request.redirectChain():[];const inherited=chain.some(parent=>mediaSeeds.has(parent.url()));const relevant=MEDIA_RE.test(url)||inherited||Boolean(kind);if(!relevant)return;let item=byUrl.get(url);if(!item){item=makeObservation(request,url);item.redirectedFrom=chain.length?chain[chain.length-1].url():'';byUrl.set(url,item);observations.push(item);}item.responseStatus=status;item.responseContentType=contentType;if(status>=200&&status<300&&isHttpsRemote(url)&&kind){item.finalUrl=url;item.finalStatus=status;item.finalContentType=contentType;item.finalKind=kind;}
    }catch{}});
    await page.goto(pageUrl.href,{waitUntil:'domcontentloaded',timeout:timeoutMs});await sleep(700);const before=await pageDiagnostics(page);phase='channel-select';const selection=await clickSelectedChannel(page,body?.channel||{});if(selection.clicked)await sleep(900);phase='playback';await nudgePlayback(page);const remaining=Math.max(0,Math.min(5000,timeoutMs-(Date.now()-started)));if(remaining)await sleep(remaining);const after=await pageDiagnostics(page);
    return{service:'WebTV Browser Resolver',version:VERSION,url:pageUrl.href,elapsedMs:Date.now()-started,observations:observations.slice(0,MAX_OBSERVATIONS),apiObservations:apiObservations.slice(0,MAX_API_OBSERVATIONS),diagnostics:{before,selection,after},limits:{timeoutMs,maxObservations:MAX_OBSERVATIONS,maxApiObservations:MAX_API_OBSERVATIONS}};
  }finally{if(browser){try{await browser.close();}catch{}}}
}

export default {async fetch(request,env){const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/')return json({service:'WebTV Browser Resolver',version:VERSION,ready:Boolean(env.BROWSER&&env.RESOLVER_SHARED_TOKEN),browserReady:Boolean(env.BROWSER),authConfigured:Boolean(env.RESOLVER_SHARED_TOKEN),allowedPageHosts:[...ALLOWED_PAGE_HOSTS]});if(request.method!=='POST'||url.pathname!=='/resolve')return json({error:'Not found'},404);if(!env.RESOLVER_SHARED_TOKEN)return json({error:'Resolver authentication is not configured'},503);if(!authorized(request,env))return json({error:'Unauthorized'},401);let body={};try{body=await request.json();}catch{return json({error:'Invalid JSON'},400);}try{return json(await resolve(body,env));}catch(error){const message=error?.message||String(error);const status=/allowlisted|HTTPS/.test(message)?400:/timeout/i.test(message)?408:502;return json({error:message,service:'WebTV Browser Resolver',version:VERSION},status);}}};

export { ALLOWED_PAGE_HOSTS, APPROVED_HEADER_NAMES, MEDIA_RE, ERT_CHANNEL_LABELS, sanitizeHeaders, safeHeaderNames, safePageUrl, timeoutFrom, pageDiagnostics, normalizedChannelKey, responseKind, safeApiLocation };
