import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto,createHash} from 'node:crypto';
const source=fs.readFileSync(new URL('../src/admin-gate.js',import.meta.url),'utf8');
const KEY='webtv_v2_sport_return_unlocked';
async function boot({returning=false,marker=false,valid=true,replaced=false,startupMinted=false}={}){
  const classes=new Set(['admin-locked']);
  const trigger=new EventTarget(),sport=new EventTarget();trigger.setAttribute=()=>{};
  const fingerprint=createHash('sha256').update('existing-session').digest('hex');
  const storage=new Map(marker?[[KEY,fingerprint]]:[]);
  let departed;const departure=new Promise(resolve=>{departed=resolve;});
  sport.href='./sport.html';
  const context={document:{documentElement:{classList:{contains:c=>classes.has(c),toggle:(c,on)=>on?classes.add(c):classes.delete(c)}},getElementById:id=>id==='admin-unlock-trigger'?trigger:id==='sport-toggle'?sport:null},window:new EventTarget(),sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},location:{search:returning?'?from=sport':'',assign:departed},crypto:webcrypto,TextEncoder,URLSearchParams,CustomEvent:class extends Event{constructor(type,init){super(type);this.detail=init?.detail;}}};
  let token=startupMinted?'new-maintenance-session':'existing-session';
  Object.assign(context.window,{prompt:()=> '123456',alert:()=>{},WebTVRegistryAuth:{token:()=>token,login:async()=>({}),validateSession:async()=>{if(replaced)token='new-maintenance-session';return valid;}}});
  vm.runInNewContext(source,context);
  await new Promise(resolve=>setTimeout(resolve,20));
  return {classes,trigger,sport,storage,departure,fingerprint};
}
const staleMarker=await boot({marker:true});
assert(staleMarker.classes.has('admin-locked'),'fresh navigation cannot reuse a return marker');
const fresh=await boot();
assert(fresh.classes.has('admin-locked'),'fresh entry must remain locked even on a trusted device');
fresh.trigger.dispatchEvent(new Event('click'));await new Promise(resolve=>setImmediate(resolve));
assert(fresh.classes.has('admin-unlocked'),'successful PIN unlock must reveal the rail');
fresh.sport.dispatchEvent(new Event('click',{cancelable:true}));await fresh.departure;
assert.equal(fresh.storage.get(KEY),fresh.fingerprint,'SPORT departure must remember an explicit UI unlock');
const returned=await boot({returning:true,marker:true});
assert(returned.classes.has('admin-unlocked'),'SPORT return must restore the already-authorized rail');
assert.equal(returned.storage.has(KEY),false,'return marker is consumed once');
const expired=await boot({returning:true,marker:true,valid:false});
assert(expired.classes.has('admin-locked'),'expired authentication cannot restore the rail');
const replacement=await boot({returning:true,marker:true,replaced:true});
assert(replacement.classes.has('admin-locked'),'minting a replacement session cannot validate the existing SPORT session');
const startupReplacement=await boot({returning:true,marker:true,startupMinted:true});
assert(startupReplacement.classes.has('admin-locked'),'a session minted before gate startup cannot replace the departed session');
const publicReturn=await boot({returning:true});
assert(publicReturn.classes.has('admin-locked'),'direct SPORT visits cannot unlock the rail');
returned.trigger.dispatchEvent(new Event('click'));
assert(returned.classes.has('admin-locked'),'explicit lock closes the rail');
console.log('admin SPORT return behavior PASS');
